### ISSUE TITLE
inline needed?

### ISSUE THREAD

**Issue by zweistein-frm2** [timniederhausen/asio-extensions#4]
Hello, 
I have a small link problem which happens only on Linux while on Windows there are no problems.
Maybe worthwhile an update of master?  
Best regards
Andreas
with the following inline addition everything works fine:
--- a/include/asioext/detail/impl/posix_file_ops.cpp
+++ b/include/asioext/detail/impl/posix_file_ops.cpp
@@ -162,7 +162,7 @@ file_attrs native_to_file_attrs(uint32_t native) ASIOEXT_NOEXCEPT

-bool stat_to_times(const struct stat& st,
+inline bool stat_to_times(const struct stat& st,

**Comment by timniederhausen** [comment]
Very good point, it appears I only test the separate-compilation mode as part of the CI.
I'll fix that, thanks for reporting it!

**Comment by timniederhausen** [comment]
All fixed, thanks again for reporting it
